/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.TypedQuery;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import uas.Buku;
import uas.Peminjamanskripsi;
import uas.Skripsi_1;
import static view.TambahPeminjamanBuku.date;

/**
 *
 * @author HP
 */
public class TambahPeminjamanSkripsi extends javax.swing.JFrame {

    /**
     * Creates new form TambahPeminjamanSkripsi
     */
    private Timer refreshTimer;

    private Connection conn;

    public void peringatan(String pesan) {
        JOptionPane.showMessageDialog(rootPane, pesan);
    }
    ArrayList<Peminjamanskripsi> peminjamanskripsi;
    ArrayList<Skripsi_1> skripsi;

    public static String date(Date date) {
        SimpleDateFormat format = new SimpleDateFormat("dd-MMMM-yyyy");
        return format.format(date);
    }

    private void tampil() {
        EntityManager entityManager = Persistence.createEntityManagerFactory("UASPU").createEntityManager();
        entityManager.getTransaction().begin();
        TypedQuery<Peminjamanskripsi> querySelectAll = entityManager.createNamedQuery("Peminjamanskripsi.findAll", uas.Peminjamanskripsi.class);
        List<Peminjamanskripsi> results = querySelectAll.getResultList();

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        for (Peminjamanskripsi data : results) {
            Object[] baris = new Object[9];
            baris[0] = data.getIdpeminjaman();
            baris[1] = data.getNama();
            baris[2] = data.getNim();
            baris[3] = data.getProdi();
            baris[4] = data.getAngkatan();
            
            if (data.getIdskripsi() != null) {
                baris[5] = data.getIdskripsi().getIdskripsi(); 
            }else{
                baris[5] = ""; //atau nilai default yg sesuai jika data.getidbuku null
            }
          
            baris[6] = data.getJudulskripsi();
            baris[7] = date(data.getTanggalpinjam());
            baris[8] = date(data.getTanggalkembali());

            model.addRow(baris);
        }
        entityManager.getTransaction().commit();
        entityManager.close();
    }

    private void tampilskripsi() {
        EntityManager entityManager = Persistence.createEntityManagerFactory("UASPU").createEntityManager();
        entityManager.getTransaction().begin();
        TypedQuery<Skripsi_1> querySelectAll = entityManager.createNamedQuery("Skripsi_1.findAll", Skripsi_1.class);
        List<Skripsi_1> results = querySelectAll.getResultList();
        DefaultTableModel model = (DefaultTableModel) jTableskripsi.getModel();
        model.setRowCount(0);
        for (Skripsi_1 data : results) {

            Object[] baris = new Object[5];
            baris[0] = data.getIdskripsi();
            baris[1] = data.getJudul();
            baris[2] = data.getPengarang();
            baris[3] = data.getTahun();
            baris[4] = data.getHalaman();

            model.addRow(baris);
        }
        entityManager.getTransaction().commit();
        entityManager.close();

    }

    private void kosongkan_form() {
        jTextFieldid.setEditable(true);
        jTextFieldid.setText("");
        jTextFieldnama.setText("");
        jTextFieldnim.setText("");
        jTextFieldprodi.setText("");
        jTextFieldangkatan.setText("");
        jDatepinjam.setDate(null);
        jDatekembali.setDate(null);
        jTextFieldidskripsi.setText("");
        jTextFieldjudulskripsi.setText("");

    }

    public TambahPeminjamanSkripsi() {
        
            initComponents();
            
            tampil();
            tampilskripsi();
            // Membuat dan mengatur timer untuk auto-refresh setiap 5 detik (5000 milidetik)
            
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableskripsi = new javax.swing.JTable();
        jTextFieldcari2 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldjudulskripsi = new javax.swing.JTextField();
        jDatepinjam = new com.toedter.calendar.JDateChooser();
        jDatekembali = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldangkatan = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldidskripsi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldid = new javax.swing.JTextField();
        jTextFieldnama = new javax.swing.JTextField();
        jTextFieldnim = new javax.swing.JTextField();
        jTextFieldprodi = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jDialog1.setSize(new java.awt.Dimension(557, 481));

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));

        jScrollPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane2MouseClicked(evt);
            }
        });

        jTableskripsi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID SKRIPSI", "JUDUL", "PENGARANG", "TAHUN", "HALAMAN"
            }
        ));
        jTableskripsi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableskripsiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableskripsi);

        jTextFieldcari2.setText("--Cari berdasarkan--");
        jTextFieldcari2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldcari2KeyReleased(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--cari--", "Judul", "Pengarang", "Tahun" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jTextFieldcari2, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldcari2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("JUDUL SKRIPSI");

        jTextFieldjudulskripsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldjudulskripsiActionPerformed(evt);
            }
        });

        jDatepinjam.setDateFormatString("yyyy MM dd");

        jDatekembali.setDateFormatString("yyyy MM dd");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("ANGKATAN");

        jTextFieldangkatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldangkatanActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("ID SKRIPSI");

        jTextFieldidskripsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldidskripsiActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("NAMA");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("NIM");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("PRODI");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Tanggal Pinjam");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Tanggal Kembali");

        jTextFieldid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldidActionPerformed(evt);
            }
        });

        jTextFieldnim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldnimActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/q.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setBackground(new java.awt.Color(0, 153, 153));
        jTable1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID PEMINJAMAN", "NAMA", "NIM", "PRODI", "ANGKATAN", "ID SKRIPSI", "JUDUL", "Tanggal Pinjam", "Tanggal Kembali"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("ID PEMINJAMAN");

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 153, 153));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 153, 153));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("---");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jTextFieldangkatan, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 951, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jTextFieldid, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jTextFieldnama, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(jTextFieldnim, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(jTextFieldprodi, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(139, 139, 139)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDatekembali, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel8)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextFieldidskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(150, 150, 150)
                                        .addComponent(jButton1))
                                    .addComponent(jLabel6)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextFieldjudulskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(202, 202, 202)
                                        .addComponent(jButton2))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jDatepinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(202, 202, 202)
                                        .addComponent(jButton3)))))))
                .addContainerGap(54, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldidskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldjudulskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFieldnim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jDatepinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldprodi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDatekembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldangkatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldjudulskripsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldjudulskripsiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldjudulskripsiActionPerformed

    private void jTextFieldangkatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldangkatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldangkatanActionPerformed

    private void jTextFieldidskripsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldidskripsiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldidskripsiActionPerformed

    private void jTextFieldidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldidActionPerformed

    private void jTextFieldnimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldnimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldnimActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here
        int baris = jTable1.rowAtPoint(evt.getPoint());
        String idpeminjaman = jTable1.getValueAt(baris, 0).toString();
        jTextFieldid.setText(idpeminjaman);

        String nama = jTable1.getValueAt(baris, 1).toString();
        jTextFieldnama.setText(nama);

        String nim = jTable1.getValueAt(baris, 2).toString();
        jTextFieldnim.setText(nim);

        String prodi = jTable1.getValueAt(baris, 3).toString();
        jTextFieldprodi.setText(prodi);

        String pinjam = jTable1.getValueAt(baris, 7).toString();
        try {
            SimpleDateFormat format = new SimpleDateFormat("yyyy-MMMM-dd");
            java.util.Date d = format.parse(pinjam);
            jDatepinjam.setDate(d);
        } catch (ParseException e) {
            e.printStackTrace(); // Gantilah ini dengan penanganan yang sesuai
        }

        String kembali = jTable1.getValueAt(baris, 8).toString();
        try {
            SimpleDateFormat format = new SimpleDateFormat("yyyy-MMMM-dd");
            java.util.Date d = format.parse(kembali);
            jDatekembali.setDate(d);
        } catch (ParseException e) {
            e.printStackTrace(); // Gantilah ini dengan penanganan yang sesua
        }
        String idskripsi= jTable1.getValueAt(baris, 5).toString();
        jTextFieldidskripsi.setText(idskripsi);

        String judulskripsi = jTable1.getValueAt(baris, 6).toString();
        jTextFieldjudulskripsi.setText(judulskripsi);

        String angkatan = jTable1.getValueAt(baris, 4).toString();
        jTextFieldangkatan.setText(angkatan);


    }//GEN-LAST:event_jTable1MouseClicked

    

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");

        String idpeminjaman = jTextFieldid.getText();
        String nama = jTextFieldnama.getText();
        String nim = jTextFieldnim.getText();
        String prodi = jTextFieldprodi.getText();
        String angkatan = jTextFieldangkatan.getText();
        String tanggalpinjam = format.format(jDatepinjam.getDate());
        String tanggalkembali = format.format(jDatekembali.getDate());
        String idskripsi = jTextFieldidskripsi.getText();
        String judulskripsi = jTextFieldjudulskripsi.getText();

// awal persistence
        EntityManager entityManager = Persistence.createEntityManagerFactory("UASPU").createEntityManager();
        entityManager.getTransaction().begin();
        Skripsi_1 wm = entityManager.find(Skripsi_1.class, idskripsi);
        Peminjamanskripsi p = new Peminjamanskripsi();

        p.setIdpeminjaman(idpeminjaman);
        p.setNama(nama);
        p.setNim(nim);
        p.setProdi(prodi);
        p.setAngkatan(angkatan);
        try {
            Date datePeminjaman = format.parse(tanggalpinjam);// Ambil langsung Date dari JDateChooser
            Date dateKembali = format.parse(tanggalkembali); // Ambil langsung Date dari JDateChooser
            p.setTanggalpinjam(datePeminjaman);
            p.setTanggalkembali(dateKembali);
        } catch (ParseException e) {
            e.printStackTrace();
        }

        p.setIdskripsi(wm);
        p.setJudulskripsi(judulskripsi);
        entityManager.persist(p);

        entityManager.getTransaction().commit();
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        tampil();
        
// akhir persistence
         if (!idskripsi.isEmpty() && !idpeminjaman.isEmpty() && nama.isEmpty() && nim.isEmpty() && prodi.isEmpty() && angkatan.isEmpty() && judulskripsi.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Save anda gagal");

            new TambahPeminjamanSkripsi().setVisible(true);
            this.dispose();

            kosongkan_form();
        } else {
            JOptionPane.showMessageDialog(this, "Save success");

            kosongkan_form();
        }
// akhir persistence
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");

        String idpeminjaman = jTextFieldid.getText();
        String nama = jTextFieldnama.getText();
        String nim = jTextFieldnim.getText();
        String prodi = jTextFieldprodi.getText();
        String angkatan = jTextFieldangkatan.getText();
        String idskripsi = jTextFieldidskripsi.getText();
        String judulskripsi = jTextFieldjudulskripsi.getText();

        String tanggalpinjam = format.format(jDatepinjam.getDate());
        String tanggalkembali = format.format(jDatekembali.getDate());

// awal persistence
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("UASPU");
        EntityManager em = emf.createEntityManager();
        Skripsi_1 wm = em.find(Skripsi_1.class, idskripsi);
        Peminjamanskripsi p = new Peminjamanskripsi();
        
        p.setIdpeminjaman(idpeminjaman);
        p.setNama(nama);
        p.setNim(nim);
        p.setProdi(prodi);
        p.setAngkatan(angkatan);
        try {
            Date datePeminjaman = format.parse(tanggalpinjam);// Ambil langsung Date dari JDateChooser
            Date dateKembali = format.parse(tanggalkembali); // Ambil langsung Date dari JDateChooser
            p.setTanggalpinjam(datePeminjaman);
            p.setTanggalkembali(dateKembali);
        } catch (ParseException e) {
            e.printStackTrace();
        }

        p.setIdskripsi(wm);
        
        p.setJudulskripsi(judulskripsi);
        

        em.getTransaction().begin();
        em.merge(p);
        em.getTransaction().commit();

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        tampil();
        
        if (!idskripsi.isEmpty() && !idpeminjaman.isEmpty() && nama.isEmpty() && nim.isEmpty() && prodi.isEmpty() && angkatan.isEmpty() && judulskripsi.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Update anda gagal");

            new TambahPeminjamanSkripsi().setVisible(true);
            this.dispose();

            kosongkan_form();
        } else {
            JOptionPane.showMessageDialog(this, "Update success");

            kosongkan_form();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String idpeminjaman = jTextFieldid.getText().trim();
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("UASPU");
        EntityManager em = emf.createEntityManager();
        em.getTransaction().begin();

        Peminjamanskripsi p = em.find(Peminjamanskripsi.class, idpeminjaman);

        em.remove(p);
        em.getTransaction().commit();
        // akhir persistence
        
        if (!idpeminjaman.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Delete Data Berhasil");

            new TambahPeminjamanBuku().setVisible(true);
            this.dispose();

            kosongkan_form();
        } else {
            JOptionPane.showMessageDialog(this, "Delete Data Gagal");

            kosongkan_form();
        }
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
        int baris = jTable1.rowAtPoint(evt.getPoint());
        String idpeminjaman = jTable1.getValueAt(baris, 0).toString();
        jTextFieldid.setText(idpeminjaman);

        String nama = jTable1.getValueAt(baris, 1).toString();
        jTextFieldnama.setText(nama);

        String nim = jTable1.getValueAt(baris, 2).toString();
        jTextFieldnim.setText(nim);

        String prodi = jTable1.getValueAt(baris, 3).toString();
        jTextFieldprodi.setText(prodi);

        String angkatan = jTable1.getValueAt(baris, 4).toString();
        jTextFieldangkatan.setText(angkatan);

        String idskripsi = jTable1.getValueAt(baris, 5).toString();
        jTextFieldangkatan.setText(angkatan);

        String judulbuku = jTable1.getValueAt(baris, 6).toString();
        jTextFieldjudulskripsi.setText(judulbuku);

        String pinjam = jTable1.getValueAt(baris, 7).toString();
        try {
            SimpleDateFormat format = new SimpleDateFormat("yyyy-MMMM-dd");
            java.util.Date d = format.parse(pinjam);
            jDatepinjam.setDate(d);
        } catch (ParseException e) {
            e.printStackTrace(); // Gantilah ini dengan penanganan yang sesuai
        }

        String kembali = jTable1.getValueAt(baris, 8).toString();
        try {
            SimpleDateFormat format = new SimpleDateFormat("yyyy-MMMM-dd");
            java.util.Date d = format.parse(kembali);
            jDatekembali.setDate(d);
        } catch (ParseException e) {
            e.printStackTrace(); // Gantilah ini dengan penanganan yang sesua
        }


    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void jTextFieldcari2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldcari2KeyReleased
        // TODO add your handling code here:
        try {
            String selection = (String) jComboBox2.getSelectedItem();

            String searchTerm = jTextFieldcari2.getText().trim();

            // Building the JPA query dynamically based on the selected criteria
            String queryString = "SELECT s FROM Skripsi_1 s WHERE ";

            switch (selection.toLowerCase()) {
                case "idskripsi":
                    queryString += "LOWER(s.idskripsi) LIKE LOWER(:searchTerm)";
                    break;
                case "judul":
                    queryString += "LOWER(s.judul) LIKE LOWER(:searchTerm)";
                    break;
                case "pengarang":
                    queryString += "LOWER(s.pengarang) LIKE LOWER(:searchTerm)";
                    break;
                case "tahun":
                    queryString += "LOWER(s.tahun) LIKE LOWER(:searchTerm)";
                    break;
                case "halaman":
                    queryString += "LOWER(s.halaman) LIKE LOWER(:searchTerm)";
                    break;
                default:
                    throw new IllegalArgumentException("No search criteria selected.");
            }

            // Create and execute the JPA query
            EntityManager em = null;

            try {
                EntityManagerFactory emf = Persistence.createEntityManagerFactory("UASPU");
                em = emf.createEntityManager();

                TypedQuery<Skripsi_1> query = em.createQuery(queryString, Skripsi_1.class);
                query.setParameter("searchTerm", "%" + searchTerm + "%");

                List<Skripsi_1> results = query.getResultList();

                DefaultTableModel dataModel = new DefaultTableModel();

                // Add columns to the model
                dataModel.addColumn("ID SKRIPSI");
                dataModel.addColumn("JUDUL");
                dataModel.addColumn("PENGARANG");
                dataModel.addColumn("TAHUN");
                dataModel.addColumn("HALAMAN");

                // ... tambahkan kolom lain sesuai kebutuhan
                // Add rows to the model
                for (Skripsi_1 result : results) {
                    Object[] rowData = {
                        result.getIdskripsi(),
                        result.getJudul(),
                        result.getPengarang(),
                        result.getTahun(),
                        result.getHalaman(),};
                    dataModel.addRow(rowData);
                }

                // Set jTableBuku with the created model
                jTableskripsi.setModel(dataModel);

            } catch (IllegalArgumentException ex) {
                // Handle the case where no search criteria selected
                ex.printStackTrace();
            } catch (Exception ex) {
                // Handle other exceptions
                ex.printStackTrace();
            } finally {
                if (em != null && em.isOpen()) {
                    em.close();
                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jTextFieldcari2KeyReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jDialog1.setVisible(true);
        jDialog1.setLocationRelativeTo(this);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jScrollPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane2MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jScrollPane2MouseClicked

    private void jTableskripsiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableskripsiMouseClicked
        // TODO add your handling code here:
        int baris = jTableskripsi.rowAtPoint(evt.getPoint());
        String idskripsi = jTableskripsi.getValueAt(baris, 0).toString();
        jTextFieldidskripsi.setText(idskripsi);

        String judulskripsi = jTableskripsi.getValueAt(baris, 1).toString();
        jTextFieldjudulskripsi.setText(judulskripsi);
    }//GEN-LAST:event_jTableskripsiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TambahPeminjamanSkripsi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TambahPeminjamanSkripsi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TambahPeminjamanSkripsi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TambahPeminjamanSkripsi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TambahPeminjamanSkripsi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox2;
    private com.toedter.calendar.JDateChooser jDatekembali;
    private com.toedter.calendar.JDateChooser jDatepinjam;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableskripsi;
    private javax.swing.JTextField jTextFieldangkatan;
    private javax.swing.JTextField jTextFieldcari2;
    private javax.swing.JTextField jTextFieldid;
    private javax.swing.JTextField jTextFieldidskripsi;
    private javax.swing.JTextField jTextFieldjudulskripsi;
    private javax.swing.JTextField jTextFieldnama;
    private javax.swing.JTextField jTextFieldnim;
    private javax.swing.JTextField jTextFieldprodi;
    // End of variables declaration//GEN-END:variables
}
